# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.5.0"

pre_release = false

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.6/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]
    [notes.binfmt_misc]
        title = "binfmt_misc"
        description = """\
`binfmt_misc` Linux module extension is now supported as Talos System Extension.
"""
    [notes.rk3588]
        title = "RK3588"
        description = """\
RK3588 kernel modules is now supported as Talos System Extension. (Turing RK1 board support)
"""

    [notes.updates]
        title = "Component Updates"
        description = """\
* Linux Kernel: 6.6.7
"""


[make_deps]
